# Generated by Django 4.0.6 on 2022-08-06 19:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.TextField(max_length=50, unique=True, verbose_name="Client's ID")),
                ('phone', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='номер телефона клиента в формате 7XXXXXXXXXX (X - цифра от 0 до 9)', regex='^7\\w{10}$')], verbose_name='Мобильный телефон')),
                ('code', models.PositiveIntegerField(verbose_name='Код мобильного оператора')),
                ('tag', models.CharField(blank=True, max_length=50, verbose_name='Тэги для поиска')),
                ('time_zone', models.CharField(max_length=10, verbose_name='Часовой пояс')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.TextField(max_length=200, unique=True, verbose_name="User's ID")),
                ('message', models.TextField(max_length=3000, verbose_name='Type something here')),
                ('codes', models.CharField(blank=True, max_length=50, verbose_name='Mobile operator codes')),
                ('tags', models.CharField(blank=True, max_length=50, verbose_name='Tags for searching')),
                ('startingTime', models.DateTimeField(verbose_name='launching the services')),
                ('endingTime', models.DateTimeField(verbose_name='Terminating services')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'расссылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=15, verbose_name='Статус отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='newsletter.client')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='newsletter.mailing')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
